services:
  vnc:
    build: ./vnc
    ports:
      - "6901:6901"     # noVNC
      - "9222:9222"     # Chrome DevTools
      - "7000:7000"     # Playwright API
    networks: [small_browser_net]
    healthcheck:                      
      test: ["CMD", "curl", "-f", "http://localhost:7000/healthz"]
      interval: 5s
      timeout: 2s
      retries: 12
    volumes:
      - .:/app 

  web:
    build: ./web
    working_dir: /app/web         
    command: python -u app.py   

    env_file:                     
      - .env       
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:                       
      vnc:
        condition: service_healthy
    networks: [small_browser_net]

networks:
  small_browser_net:
    name: small_browser_net
