"""Domain specific language (DSL) models and registry for browser automation."""

from .models import (
    ActionBase,
    ActionResult,
    ClickAction,
    ExtractAction,
    FocusIframeAction,
    NavigateAction,
    PressKeyAction,
    ScrollAction,
    ScreenshotAction,
    SelectAction,
    Selector,
    SelectorLike,
    SwitchTabAction,
    TypeAction,
    WaitAction,
    WaitCondition,
    WaitForSelector,
    WaitForState,
    WaitForTimeout,
    ScrollTarget,
    TabTarget,
    FrameTarget,
    AssertAction,
)
from .registry import ActionRegistry, RunPlan, RunRequest, registry
from .resolution import ResolutionAttempt, ResolvedNode

__all__ = [
    "ActionBase",
    "ActionResult",
    "ClickAction",
    "ExtractAction",
    "FocusIframeAction",
    "NavigateAction",
    "PressKeyAction",
    "ScrollAction",
    "ScreenshotAction",
    "SelectAction",
    "Selector",
    "SelectorLike",
    "SwitchTabAction",
    "TypeAction",
    "WaitAction",
    "WaitCondition",
    "WaitForSelector",
    "WaitForState",
    "WaitForTimeout",
    "ScrollTarget",
    "TabTarget",
    "FrameTarget",
    "AssertAction",
    "RunPlan",
    "RunRequest",
    "ActionRegistry",
    "registry",
    "ResolutionAttempt",
    "ResolvedNode",
]
